### ISSUE TITLE
Unnecessary?

### ISSUE THREAD

**Issue by baskerville** [mdo/ocean-terminal#1]
Chris Kempson's [base16-builder](https://github.com/chriskempson/base16-builder) has a template for _Terminal.app_, so you can just issue: `./base16 -s schemes/ocean.yml` and grab the generated profiles in `output/terminal-app`.

**Comment by mdo** [comment]
That wasn't at all clear from the main base16 repo, so I went and made this on my own. I'm fine leaving it as-is and not using the builder right now. Thanks for mentioning it though!
